#!/bin/bash

flag="0"
balance=0
idIsFound="0"
INFILE=/Bank_system/users_bank.csv
newAccount () {

echo "Enter your name "
        read name
        echo "Enter your ID "
        read _id
        echo "Enter your password "
        read password

        echo "$_id:$name:$password:$balence" >> /Bank_system/users_bank.csv
}
printf "\nwelcome to Tuwaiq Bank\n"

echo "Do you have an account yes or no "
read have_Acc

if [ "$have_Acc" == "yes" ]
then

echo " Enter your ID"
read _id
echo "Enter your password"
read password


IFS=$'\n' # set the Internal Field Separator to newline
for LINE in $(cat "$INFILE")
do

        id=`echo "$LINE" | cut -d: -f1`

        pass=`echo "$LINE" | cut -d: -f3`

if [ "$_id" == "$id"  ]
then
        idIsFound="1"

if [ "$password" == "$pass" ]
        then

        balance=`echo "$LINE" | cut -d":" -f4`


while [ $flag -eq "0" ];
do
echo "1- Current amount "
echo "2- Deposit"
echo "3- Withdraw"
echo "4- Exit"
echo "Choose the number"
read choice
if [ $choice == "1" ]
        then
 echo "Your current balence is: $balance"

elif [ $choice == "2" ]
then
        echo "How much do you want to Deposit?"

read Deposit_amount
 echo "Added successful"
sum=`expr $balance + $Deposit_amount`
     sed -i "s/$balance/$sum/" $INFILE
   #awk `/_id/ { print $4 =$sum }` $LINE
         balance=`expr $balance + $Deposit_amount`

elif [ $choice == "3" ]
then
      echo "How much do you want to Withdraw?"
        read Withdraw_amount
        if [ "$balance" -gt "$Withdraw_amount" ]
        then
         echo "Done successful"
          Withdraw=`expr $balance - $Withdraw_amount`
        sed -i "s/$balance/$Withdraw/" $INFILE
#       awk `/_id/ { print $4 =$Withdraw }` $LINE
        balance=$Withdraw
elif [ $balance -lt $Withdraw_amount ]
then
        echo "Your balance is less than  $Withdraw_amount"

fi
              elif [ $choice == "4" ]
then

        flag=1
        echo " see you later"

fi

done
else

        echo "invalide id or password "
echo " Enter your ID"
read _id
echo "Enter your password"
read password
fi
else
continue
fi
if [ idIsFound == "1" ]
then
echo " Your ID not found please creat new account"
newAccount
fi

done
elif [ "$have_Acc" == "no" ]
then
newAccount
else
        echo "invalide option "
        newAccount
fi
